# Generated by Django 3.2.6 on 2021-08-09 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100, verbose_name='メンバの指名')),
                ('email', models.EmailField(max_length=254, verbose_name='メンバーのアドレス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理者名')),
            ],
            options={
                'verbose_name': 'メンバー情報',
                'verbose_name_plural': 'メンバー情報',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('contents', models.TextField(verbose_name='内容')),
                ('date', models.DateField(verbose_name='開催日時')),
                ('members', models.ManyToManyField(to='meeting.Member', verbose_name='参加メンバー')),
            ],
            options={
                'verbose_name': 'メンバー情報',
                'verbose_name_plural': 'メンバー情報',
            },
        ),
    ]
